In [1]:
# import dependencies
import pandas as pd

# Read vine table as CSV
vinedf = pd.read_csv("vine_table.csv")

In [2]:
# Check loading
vinedf

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,R18RVCKGH1SSI9,5.0,0.0,0.0,N,Y
1,R3L4L6LW1PUOFY,5.0,0.0,1.0,N,Y
2,R2J8AWXWTDX2TF,5.0,0.0,0.0,N,Y
3,R1PR37BR7G3M6A,1.0,2.0,3.0,N,Y
4,R3BDDDZMZBZDPU,4.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
2642429,RLI7EI10S7SN0,4.0,26.0,26.0,N,N
2642430,R1F3SRK9MHE6A3,4.0,18.0,18.0,N,N
2642431,R23V0C4NRJL8EM,4.0,9.0,16.0,N,N
2642432,R13ZAE1ATEUC1T,5.0,0.0,0.0,N,N
2642433,RE8J5O2GY04NN,5.0,0.0,0.0,N,N

In [3]:
# Filter out any products with less than 20 votes
filtered_vinedf = vinedf[vinedf["total_votes"] > 20]
filtered_vinedf

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
190,R243UXMMSSZVS6,2.0,254.0,254.0,N,Y
503,R2P92EHR0S5GBB,1.0,110.0,159.0,N,Y
556,RN93Z4XPNAANY,5.0,31.0,31.0,N,Y
754,R1O74T9XO3OPQ4,5.0,38.0,38.0,N,Y
1021,R3DMIHE5BMUT0R,3.0,21.0,21.0,N,Y
...,...,...,...,...,...,...
2642376,RFK1NQNOQYFLV,3.0,74.0,74.0,N,N
2642377,R1SF84GXC1LXVW,5.0,21.0,21.0,N,N
2642382,R3W2OYBMMOYT9G,5.0,36.0,36.0,N,N
2642383,R1TG8VNKP4DSQR,4.0,27.0,38.0,N,N
2642429,RLI7EI10S7SN0,4.0,26.0,26.0,N,N

In [4]:
# Filter out any products where the votes on the review were less than 50%
voteddf = filtered_vinedf[filtered_vinedf["helpful_votes"]/filtered_vinedf["total_votes"] >= .5]
voteddf

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
190,R243UXMMSSZVS6,2.0,254.0,254.0,N,Y
503,R2P92EHR0S5GBB,1.0,110.0,159.0,N,Y
556,RN93Z4XPNAANY,5.0,31.0,31.0,N,Y
754,R1O74T9XO3OPQ4,5.0,38.0,38.0,N,Y
1021,R3DMIHE5BMUT0R,3.0,21.0,21.0,N,Y
...,...,...,...,...,...,...
2642376,RFK1NQNOQYFLV,3.0,74.0,74.0,N,N
2642377,R1SF84GXC1LXVW,5.0,21.0,21.0,N,N
2642382,R3W2OYBMMOYT9G,5.0,36.0,36.0,N,N
2642383,R1TG8VNKP4DSQR,4.0,27.0,38.0,N,N
2642429,RLI7EI10S7SN0,4.0,26.0,26.0,N,N

In [5]:
# Establish DataFrame where the reviews of the product were sponsored
sponsoredvotesdf = voteddf[voteddf["vine"] == 'Y']
sponsoredvotesdf

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
37817,R3JIGR122X50ZV,5.0,2280.0,2314.0,Y,N
57518,R3KV8P8WLD2KKC,5.0,263.0,286.0,Y,N
117580,R2LFY2ZPJ3J7RH,4.0,36.0,38.0,Y,N
123097,R3P01OXMA0U0CA,5.0,114.0,117.0,Y,N
128223,R2SCMXBD9OQP8Z,2.0,22.0,26.0,Y,N
...,...,...,...,...,...,...
2533599,R35A0RI8N5YE6Z,2.0,35.0,38.0,Y,N
2534123,R6G4QG2BEMTDQ,5.0,70.0,72.0,Y,N
2535862,R2QD2B9UYVZVBJ,4.0,18.0,22.0,Y,N
2536481,R203FP24HCBWP9,3.0,40.0,40.0,Y,N
2538387,R11BPVZYDF6T1B,5.0,72.0,72.0,Y,N

In [6]:
# Establish DataFrame where the reviews of the product were not sponsored
notsponsoredvotesdf = voteddf[voteddf["vine"] == 'N']
notsponsoredvotesdf

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
190,R243UXMMSSZVS6,2.0,254.0,254.0,N,Y
503,R2P92EHR0S5GBB,1.0,110.0,159.0,N,Y
556,RN93Z4XPNAANY,5.0,31.0,31.0,N,Y
754,R1O74T9XO3OPQ4,5.0,38.0,38.0,N,Y
1021,R3DMIHE5BMUT0R,3.0,21.0,21.0,N,Y
...,...,...,...,...,...,...
2642376,RFK1NQNOQYFLV,3.0,74.0,74.0,N,N
2642377,R1SF84GXC1LXVW,5.0,21.0,21.0,N,N
2642382,R3W2OYBMMOYT9G,5.0,36.0,36.0,N,N
2642383,R1TG8VNKP4DSQR,4.0,27.0,38.0,N,N
2642429,RLI7EI10S7SN0,4.0,26.0,26.0,N,N

In [7]:
# Count the total number of reviews for sponsored products
sponsoredreviewcount = sponsoredvotesdf.value_counts(["review_id"]).sum()
sponsoredreviewcount

926

In [8]:
# Count the total number of reviews for nonsponsored products
nonsponsoredreviewcount = notsponsoredvotesdf.value_counts(["review_id"]).sum()
nonsponsoredreviewcount

41096

In [9]:
# Count the total number of 5-star reviews for sponsored products
fivestarsponsoredvotesdf = sponsoredvotesdf[sponsoredvotesdf["star_rating"] == 5.0]
fivestarsponsoredvotes = fivestarsponsoredvotesdf.value_counts(["review_id"]).sum()
fivestarsponsoredvotes

408

In [10]:
# Count the total number of 5-star reviews for nonsponsored products
fivestarnonsponsoredvotesdf = notsponsoredvotesdf[notsponsoredvotesdf["star_rating"] == 5.0]
fivestarnonsponsoredvotes = fivestarnonsponsoredvotesdf.value_counts(["review_id"]).sum()
fivestarnonsponsoredvotes

18104

In [11]:
# Calculate the percentage of the 5-star sponsored reviews
fivestarsponsoredvotespercent = fivestarsponsoredvotes/sponsoredreviewcount
fivestarsponsoredvotespercent

0.4406047516198704

In [12]:
# Calculate the percentage of the 5-star nonsponsored reviews
fivestarnonsponsoredvotespercent = fivestarnonsponsoredvotes/nonsponsoredreviewcount
fivestarnonsponsoredvotespercent

0.4405294919213549